[servers.local_server]
script = "../../server/server.py"
enabled = false

[servers.git]
command = "python"
args = ["-m", "mcp_server_git", "--repository", "../../"]
enabled = true

[servers.filesystem]
command = "mcp-server-filesystem"
args = ["../../"]
enabled = true